name: Run Python Notebook

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version (e.g., '3.8', '3.9', etc.)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Convert Notebook to Script
        run: jupyter nbconvert --to script "BigMart Sales Prediction - Updated.ipynb"

      - name: Run Python script
        run: python "BigMart Sales Prediction - Updated.py"
